### ISSUE TITLE
Add AV and SCAP folders as part of Setup file

### ISSUE THREAD

**Issue by lordneeko** [SuperCATDevelopers/SuperCAT#15]
The Setup process needs to include the creation of the AV (.\AV\w64\ and .\AV\DAT) and SCAP (.\DISA\)folders for the end user to add the AV and SCC command line tools.

**Comment by stevenevans1197** [comment]
I was looking at the 2.2 tool after I download and those folders should be there already

**Comment by lordneeko** [comment]
This was already done by Steve.
