### ISSUE TITLE
Modify SuperCAT to be able to run completely from command line arguments.

### ISSUE THREAD

**Issue by lordneeko** [SuperCATDevelopers/SuperCAT#26]
This function can speed up execution and can also support automated unit testing.

**Comment by VWong99** [comment]
c6981a73359ea02bbf9177a5f55737cd03ac8eac partially implements command line argument only operation. User input is still required for Serial Number confirmation and cleanup confirmation.

Example usage: 
`.\SuperCAT.ps1 -Choices "1" -System "1" -Location "1"`

**Comment by lordneeko** [comment]
This will need to be re-accomplished after PR #57 is implemented.

**Comment by lordneeko** [comment]
@VWong99  Does it work for you to just re-open this, or does it normally make sense to just create a new one?
