### ISSUE TITLE
This line appears unnecessary and currently causes an error when running

### ISSUE THREAD

**Issue by lordneeko** [SuperCATDevelopers/SuperCAT#47]
It appears that the origin of this was moving the files created by the scanner to the output location, however the -u argument already puts the files in this location.  Need to confirm what the purpose of this line it, and if it is not needed, remove it.

https://github.com/SuperCATDevelopers/SuperCAT/blob/f4313b27ed6f1bb972ddc346f66137e9500c5dc1/Tool/SuperCAT.ps1#L331

**Comment by FredericIV** [comment]
Will be fixed with pull #57

**Comment by FredericIV** [comment]
#57 pulled.
